services:
  # Aplicação Go
  api:
    container_name: suassu-api-container
    image: ghcr.io/esg-project/suassu-api:master
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - suassu-network
    restart: unless-stopped

networks:
  suassu-network:
    driver: bridge
