package seeds

// FeatureList contém a lista de nomes de features a serem populadas no banco de dados.
var FeatureList = []string{
	"Calendar",
	"Complement",
	"Conditioning",
	"Dashboard",
	"DueDateConditioning",
	"Craft",
	"License",
	"Logs",
	"Parameter",
	"Permission",
	"Product",
	"Project",
	"Proposal",
	"ProposalProduct",
	"Protocol",
	"Role",
	"TypeProduct",
	"Links",
	"User",
	"Client",
	"Technician",
	"Financial",
	"Bank",
	"EnterpriseBank",
	"PhytoAnalysis",
}
